const User = require("../models/User");
const AppError = require("../utils/AppError");
const { ROLES } = require("../config/roles");
const { generateRandomPassword } = require("../utils/tokenUtils");

/**
 * Get all users with pagination, search, and filtering
 */
const getAllUsers = async ({ page = 1, limit = 10, search, role, status }) => {
  const query = {};

  // Search by name or email
  if (search) {
    query.$or = [
      { name: { $regex: search, $options: "i" } },
      { email: { $regex: search, $options: "i" } },
    ];
  }

  if (role) query.role = role;
  if (status) query.status = status;

  // const skip = (Number(page) - 1) * Number(limit);
  const pageNum = Math.max(1, parseInt(page) || 1);
  const limitNum = Math.max(1, parseInt(limit) || 10);

  const skip = (pageNum - 1) * limitNum;

  const [users, total] = await Promise.all([
    User.find(query)
      .populate("createdBy", "name email")
      .populate("updatedBy", "name email")
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limitNum)
      .select("-password -refreshToken"),
    User.countDocuments(query),
  ]);

  return {
  users,
  pagination: {
    total,
    page: pageNum,
    limit: limitNum,
    pages: Math.ceil(total / limitNum),
  },
};

/**
 * Get a single user by ID
 * Managers cannot view admin users
 */
const getUserById = async (targetId, requestingUser) => {
  const user = await User.findById(targetId)
    .populate("createdBy", "name email")
    .populate("updatedBy", "name email")
    .select("-password -refreshToken");

  if (!user) throw new AppError("User not found.", 404);

  // Managers cannot view admin profiles
  if (requestingUser.role === ROLES.MANAGER && user.role === ROLES.ADMIN) {
    throw new AppError("You do not have permission to view this user.", 403);
  }

  return user;
};

/**
 * Create a new user (Admin only)
 * Generates password if not provided
 */
const createUser = async (data, createdByUserId) => {
  const { name, email, role = ROLES.USER, status = "active" } = data;
  let { password } = data;

  const exists = await User.findOne({ email });
  if (exists) throw new AppError("Email already in use.", 409);

  const autoGenerated = !password;
  if (autoGenerated) {
    password = generateRandomPassword();
  }

  const user = await User.create({
    name,
    email,
    password,
    role,
    status,
    createdBy: createdByUserId,
    updatedBy: createdByUserId,
  });

  return {
    user: user.toSafeObject(),
    ...(autoGenerated && { generatedPassword: password }), // Only returned once on creation
  };
};

/**
 * Update any user (Admin full / Manager limited)
 */
const updateUser = async (targetId, updates, requestingUser) => {
  const target = await User.findById(targetId);
  if (!target) throw new AppError("User not found.", 404);

  // Managers cannot update admin users
  if (requestingUser.role === ROLES.MANAGER && target.role === ROLES.ADMIN) {
    throw new AppError("You cannot modify admin users.", 403);
  }

  // Only admins can change roles
  if (updates.role && requestingUser.role !== ROLES.ADMIN) {
    throw new AppError("Only admins can change user roles.", 403);
  }

  // Only admins can change status
  if (updates.status && requestingUser.role !== ROLES.ADMIN) {
    throw new AppError("Only admins can change user status.", 403);
  }

  // Prevent admin from downgrading their own role
  if (
    requestingUser.role === ROLES.ADMIN &&
    requestingUser._id.toString() === targetId &&
    updates.role &&
    updates.role !== ROLES.ADMIN
  ) {
    throw new AppError("Admins cannot downgrade their own role.", 400);
  }

  const allowedFields = ["name", "email", "role", "status"];
  allowedFields.forEach((field) => {
    if (updates[field] !== undefined) {
      target[field] = updates[field];
    }
  });

  target.updatedBy = requestingUser._id;
  await target.save();

  return target.toSafeObject();
};

/**
 * Update own profile (any authenticated user)
 */
const updateOwnProfile = async (userId, updates) => {
  const user = await User.findById(userId).select("+password");
  if (!user) throw new AppError("User not found.", 404);

  // Allowed self-update fields
  if (updates.name) user.name = updates.name;
  if (updates.password) user.password = updates.password; // Will be hashed by pre-save hook

  user.updatedBy = userId;
  await user.save();

  return user.toSafeObject();
};

/**
 * Soft delete / deactivate a user (Admin only)
 * We never hard-delete — just set status to 'inactive'
 */
const deleteUser = async (targetId, requestingUserId) => {
  if (targetId === requestingUserId.toString()) {
    throw new AppError("You cannot delete your own account.", 400);
  }

  const user = await User.findById(targetId);
  if (!user) throw new AppError("User not found.", 404);

  user.status = "inactive";
  user.updatedBy = requestingUserId;
  await user.save();

  return { message: "User deactivated successfully." };
};

module.exports = {
  getAllUsers,
  getUserById,
  createUser,
  updateUser,
  updateOwnProfile,
  deleteUser,
};
